name: Deploy Birthday Reminder Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Deploy
        env:
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}

          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

          BIRTHDAY_BOT_NAME: ${{ secrets.BIRTHDAY_BOT_NAME }}
          BIRTHDAY_BOT_TOKEN: ${{ secrets.BIRTHDAY_BOT_TOKEN }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_HOST >> ~/.ssh/known_hosts

          echo "MYSQL_DATABASE=$MYSQL_DATABASE" > .env
          echo "MYSQL_USER=$MYSQL_USER" >> .env
          echo "MYSQL_PASSWORD=$MYSQL_PASSWORD" >> .env
          echo "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD" >> .env
          echo "BIRTHDAY_BOT_NAME=$BIRTHDAY_BOT_NAME" >> .env
          echo "BIRTHDAY_BOT_TOKEN=$BIRTHDAY_BOT_TOKEN" >> .env
          
          echo "SERVER_USER=${SERVER_USER}" | wc -c
          echo "SERVER_HOST=${SERVER_HOST}" | wc -c
  
          scp -i ~/.ssh/id_rsa .env $SERVER_USER@$SERVER_HOST:/home/belnitskii/birthday-reminder-bot/.env
          ssh -i ~/.ssh/id_rsa $SERVER_USER@$SERVER_HOST << 'EOF'
          
          cd /home/belnitskii/birthday-reminder-bot
          git fetch origin
          git reset --hard origin/main
          git pull origin main

          mvn clean package -DskipTests
          docker-compose down || true
          docker-compose build --no-cache
          docker-compose up -d
          EOF
